### ISSUE TITLE
MySQL connection error

### ISSUE THREAD

**Issue by zer0ttl** [appsecco/dvna#5]
Hi,

I followed the instructions to setup the DVNA using the official docker file.

When I run the docker image I get the following error.

``wait-for-it.sh: waiting 300 seconds for mysql-db:3306
wait-for-it.sh: mysql-db:3306 is available after 0 seconds

> dvna@0.0.1 start /app
> node server.js

Fri, 23 Mar 2018 12:05:06 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules/sequelize/lib/sequelize.js:236:13
Unable to connect to the database: { SequelizeAccessDeniedError: Access denied for user 'dvna'@'172.17.0.3' (using password: YES)
    at Utils.Promise.tap.then.catch.err (/app/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:141:19)
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/app/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
  name: 'SequelizeAccessDeniedError',
  parent: 
   { Error: Access denied for user 'dvna'@'172.17.0.3' (using password: YES)
    at Packet.asError (/app/node_modules/mysql2/lib/packets/packet.js:713:13)
    at ClientHandshake.Command.execute (/app/node_modules/mysql2/lib/commands/command.js:28:22)
    at Connection.handlePacket (/app/node_modules/mysql2/lib/connection.js:515:28)
    at PacketParser.onPacket (/app/node_modules/mysql2/lib/connection.js:94:16)
    at PacketParser.executeStart (/app/node_modules/mysql2/lib/packet_parser.js:77:14)
    at Socket.<anonymous> (/app/node_modules/mysql2/lib/connection.js:102:29)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
     code: 'ER_ACCESS_DENIED_ERROR',
     errno: 1045,
     sqlState: '28000',
     sqlMessage: 'Access denied for user \'dvna\'@\'172.17.0.3\' (using password: YES)' },
  original: 
   { Error: Access denied for user 'dvna'@'172.17.0.3' (using password: YES)
    at Packet.asError (/app/node_modules/mysql2/lib/packets/packet.js:713:13)
    at ClientHandshake.Command.execute (/app/node_modules/mysql2/lib/commands/command.js:28:22)
    at Connection.handlePacket (/app/node_modules/mysql2/lib/connection.js:515:28)
    at PacketParser.onPacket (/app/node_modules/mysql2/lib/connection.js:94:16)
    at PacketParser.executeStart (/app/node_modules/mysql2/lib/packet_parser.js:77:14)
    at Socket.<anonymous> (/app/node_modules/mysql2/lib/connection.js:102:29)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
     code: 'ER_ACCESS_DENIED_ERROR',
     errno: 1045,
     sqlState: '28000',
     sqlMessage: 'Access denied for user \'dvna\'@\'172.17.0.3\' (using password: YES)' } }
An error occurred while creating the table: { SequelizeAccessDeniedError: Access denied for user 'dvna'@'172.17.0.3' (using password: YES)
    at Utils.Promise.tap.then.catch.err (/app/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:141:19)
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/app/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
  name: 'SequelizeAccessDeniedError',
  parent: 
   { Error: Access denied for user 'dvna'@'172.17.0.3' (using password: YES)
    at Packet.asError (/app/node_modules/mysql2/lib/packets/packet.js:713:13)
    at ClientHandshake.Command.execute (/app/node_modules/mysql2/lib/commands/command.js:28:22)
    at Connection.handlePacket (/app/node_modules/mysql2/lib/connection.js:515:28)
    at PacketParser.onPacket (/app/node_modules/mysql2/lib/connection.js:94:16)
    at PacketParser.executeStart (/app/node_modules/mysql2/lib/packet_parser.js:77:14)
    at Socket.<anonymous> (/app/node_modules/mysql2/lib/connection.js:102:29)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
     code: 'ER_ACCESS_DENIED_ERROR',
     errno: 1045,
     sqlState: '28000',
     sqlMessage: 'Access denied for user \'dvna\'@\'172.17.0.3\' (using password: YES)' },
  original: 
   { Error: Access denied for user 'dvna'@'172.17.0.3' (using password: YES)
    at Packet.asError (/app/node_modules/mysql2/lib/packets/packet.js:713:13)
    at ClientHandshake.Command.execute (/app/node_modules/mysql2/lib/commands/command.js:28:22)
    at Connection.handlePacket (/app/node_modules/mysql2/lib/connection.js:515:28)
    at PacketParser.onPacket (/app/node_modules/mysql2/lib/connection.js:94:16)
    at PacketParser.executeStart (/app/node_modules/mysql2/lib/packet_parser.js:77:14)
    at Socket.<anonymous> (/app/node_modules/mysql2/lib/connection.js:102:29)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
     code: 'ER_ACCESS_DENIED_ERROR',
     errno: 1045,
     sqlState: '28000',
     sqlMessage: 'Access denied for user \'dvna\'@\'172.17.0.3\' (using password: YES)' } }

**Comment by subashsn** [comment]
Hey zer0ttl,

Sorry for the delayed response.

I was unable to replicate the error. Are you using the same `vars.env` file to start the database and dvna containers? Can you try with the example `vars.env` provided in the README and let me know if it works.

Meanwhile, if you've already fixed this, please let me know and close the issue. Thanks

**Comment by zer0ttl** [comment]
Hye subashsn,

I was able to get it up and running the other day. I used the example vars.env as you mentioned.

Thanks.
